name: VitalityTest
favicon: null
layout_spectrum: 0.5587329585105181
typography_spectrum: 0.6669231257401407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6522935663815588
  lightness: 0.15098814968951046
  saturation: 0.028601812198758125
  rhythmicContrast: 0.4185783416032791
purpose: []
